# Numpy Introduction

### Installing Numpy

conda iinstall numpy
atau
pip install numpy

In [2]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7 , 8], [9, 10, 11, 12]])

print(a[0])

[1 2 3 4]


In [3]:
[[0., 0., 0.],
[1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

In [4]:
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

TypeError: array() missing required argument 'object' (pos 0)

In [7]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
# Or even an empty array!
# The function empty creates an array whose initial content is random and depends on the state of the memory

np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
# you can create an array with a range of elements

print(np.arange(4))
print(np.arange(0,10,2)) #(start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [ ]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

## Add, Remove, and Sort

In [ ]:
np.append()
np.delete()
np.sort()

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])

In [ ]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [ ]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

## Shape and Size

In [ ]:
ndarray.ndim() #jumlah axes, dimensi dr array
ndarray.size() #jumlah total elemen array
ndarray.shape() #menampilkan tuple integer

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         
                         [[0, 1, 2, 3],
                         [4, 5, 6, 7]],
                        
                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [ ]:
array_example.ndim

3

In [ ]:
array_example.size

24

In [ ]:
array_example.shape

(3, 2, 4)

In [ ]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [ ]:
arr_one.ndim

2

In [ ]:
arr_one.size

5

In [ ]:
arr_one.shape

(1, 5)

## Reshape

In [ ]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])


## Convert 1D to 2D

In [ ]:
np.newaxis
np.expand_dims

<function numpy.expand_dims(a, axis)>

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
# you can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [ ]:
# you can convert a 1d array to a row vector by interesting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [ ]:
# for a column vector, you can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
# you can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [ ]:
# you can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing and Slicing

In [ ]:
data = np.array([1, 2, 3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#you can easily print all of the values in the array that are more than 5
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [ ]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [ ]:
# you can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [ ]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [ ]:
slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [ ]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [ ]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [ ]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
# or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [ ]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                   [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [ ]:
# if u wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# u can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# using the copy method will make a complete copy of the array and its data (a deep copy)

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic array operations

In [ ]:
# Addition, Subtraction, Multiplication, Division, and More..

In [ ]:
a = np.array([1, 2, 3, 4])

# add all of the elements in the array
a.sum()

10

In [ ]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [ ]:
# u can sum the rows
b.sum(axis=0)

array([3, 3])

In [ ]:
# u can sum the columns
b.sum(axis=1)

array([2, 4])

In [ ]:
data = np.array([1, 2])
data

array([1, 2])

In [ ]:
ones = np.ones(2)
ones

array([1., 1.])

In [ ]:
data + ones

array([2., 3.])

In [ ]:
data * data

array([1, 4])

In [ ]:
data / data

array([1., 1.])

## Broadcasting

In [ ]:
data * 2

array([2, 4])

## More Array Operations

In [ ]:
# Maximum, minimum, sum, mean, product, standar deviation, and more..

In [ ]:
data.max()
data.min()
data.sum()

3

## Matrices

### Creating Matrices

In [ ]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.84380848, 0.92173543],
       [0.80373794, 0.66704886],
       [0.34066183, 0.64898366]])

In [ ]:
print(np.ones((3,2)))
print(np.zeros((3, 2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.42569672 0.64834943]
 [0.33757155 0.4601699 ]
 [0.45103632 0.50890771]]


In [ ]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [ ]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [ ]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [ ]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [ ]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [ ]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [ ]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

In [10]:
data = np.array([[1,2], [3,4], [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [11]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [14]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [15]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [17]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [18]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [21]:
ndarr = np.array([[[1, 2], [3,4]],
                 [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [23]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [24]:
print(np.random.random((4,3,2)))

[[[0.54500848 0.07183986]
  [0.60467713 0.51409722]
  [0.680213   0.70566672]]

 [[0.44373637 0.57634997]
  [0.00706865 0.84703508]
  [0.26959146 0.27894958]]

 [[0.85878392 0.71613565]
  [0.54280352 0.11226953]
  [0.66500247 0.68296212]]

 [[0.31885425 0.86195446]
  [0.71586779 0.6984619 ]
  [0.42068735 0.53510967]]]


## Flatten N-Dimensional Array

In [25]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
# u can use flatten to flatten ur array into 1d array

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

In [1]:
error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'n' is not defined